### ISSUE TITLE
Remove glossary.yml from this repo

### ISSUE THREAD

**Issue by gvwilson** [carpentries/glosario-py#1]
`glosario/data/glossary.yml` should _not_ be in this repository - it should be downloaded dynamically during build (and included in `.gitignore` to prevent accidental addition in future).

**Comment by tonyfast** [comment]
super stoked on this project.

is the `glossary.yml` in https://github.com/carpentries/glosario/ always going to be the reference file for this project? is the idea each day the catalog will be updated from that repository?

**Comment by ian-flores** [comment]
Hi @tonyfast I implemented something similar to what you mention here today in: https://github.com/carpentries/glosario-py/blob/master/.github/workflows/build_data.yaml. Just a GH Action to download the file.
