### ISSUE TITLE
Are we supporting Python 2.7?

### ISSUE THREAD

**Issue by gvwilson** [carpentries/glosario-py#2]
`CONTRIBUTING.rst` says that contributions should work for Python 2.7 - are we supporting it?

**Comment by zkamvar** [comment]
According to the pyproject toml file, we only support anything greater or equal to 3.7.... which means that I can't install it on my default debian python, which is still on python 3.6

https://github.com/carpentries/glosario-py/blob/7ed1cf217b69cc3c62ce8886bb1224d8c4b891ea/pyproject.toml#L10

**Comment by baileythegreen** [comment]
Is this something you want to support? It looks like it comes down to (at least in the first instance) the packages being used. `sphinx` and `pygments` (a `sphinx` dependency) both require Python 3.5 or greater, and then the requirement is bumped up to 3.7 or greater by this content hash:

```
[metadata]
content-hash = "4421dd0cc019635723ac4afe9f836d7cc2afab3695d8ab5176d216b5e38c0821"
python-versions = "^3.7"
```

I don't know what that is, but it seems like you could offer a 'different' version without `sphinx` documentation for use with Python 2.7. (There might be other incompatibilities, but that would be a start. And Python version shouldn't affect how it's used, right? So you shouldn't need separate documentation for the 'different' version.)
