### ISSUE TITLE
Interest for creating Glosario.jl 

### ISSUE THREAD

**Issue by SaranjeetKaur** [carpentries/glosario-py#8]
Hello @ian-flores and @gvwilson ! I would like to create a `Glosario.jl` package for Julia inspired from `glosario-py`. Any suggestions?

**Comment by fmichonneau** [comment]
@SaranjeetKaur Thanks for your interest in creating a Julia version of Glosario :smile: That sounds like a great idea. I would suggest you start a repo to implement your idea and once it's ready we could transfer it to The Carpentries GitHub organization if it's what you'd like to do.

**Comment by SaranjeetKaur** [comment]
Okay, that is wonderful! Shall get back to you once the first version of it is ready.

**Comment by fmichonneau** [comment]
We are looking forward to it!

**Comment by ian-flores** [comment]
Hi @SaranjeetKaur I'm closing this issue but feel free to re-open it once the package is ready to be shared. Thanks! 😄
